### PR TITLE
GFF3 validator

### LINKED ISSUE #13: Suggestion - a single error message
This is me being lazy and not wanting to iterate! For discussion!!

This is my code snippet:

```
            List<Message> messages = validationResult.getErrorMessages();
            StringBuilder errorMessage = new StringBuilder();
            for (Message msg : messages) {
                errorMessage.append(msg.getMessage());
            }
            return errorMessage.toString();
```

I would like to do this instead:

```
            return validationResult.getErrorMessage();
```

For the `strict` setting we'll only have one error message anyway.

### PR DESCRIPTION
**Pull request by deepakkumar96**
Add GFF3 validator:
add a method getErrorMessage() in Validation to get a single message as String close #13

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Should we bump this to `0.1.1`? or since it's a feature, `0.2.0`?

**Comment by julie-sullivan** [comment]
```
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.1.jar -f=/tmp/data/ref_GRCh38.p12_top_level.gff3
Validating fasta file...
Result : Invalid File!!
Error:
	1. File is not recognized as valid Fasta format
```

I think this was covered by another ticket, but instead this should say that the filetype is required. OR guess (because file ext is gff3) GFF3.

**Comment by julie-sullivan** [comment]
```
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.1.jar -f=/tmp/data/ref_GRCh38.p12_top_level.gff3 -t=gff
Validating gff file...
Invalid validator type
```
Can we be more permissive and accept gff and gff3?

**Comment by julie-sullivan** [comment]
Also, should be case insensitive.

**Comment by deepakkumar96** [comment]
> ```
> julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.1.jar -f=/tmp/data/ref_GRCh38.p12_top_level.gff3 -t=gff
> Validating gff file...
> Invalid validator type
> ```
> 
> Can we be more permissive and accept gff and gff3?

Ok, I'll make changes to accept both 'gff' and 'gff3' as type!

**Comment by julie-sullivan** [comment]
```
Validating gff3 file...
Result : Invalid File!!
Error:
	1. Invalid gff3 file! first line must be a header line
```

Just sent an email for discussion on whether or not we should ignore this rule for now.

**Comment by julie-sullivan** [comment]
everything else looks great!

**Comment by deepakkumar96** [comment]
> everything else looks great!

whenever you are going to merge any PR, then please follow this order, 
1. first GFF3 validator PR and then,
2.  CSV validator PR(not yet complete) and then,
3. DOCS and RELEASE PR, 
just because they are dependent on each other, because I git-branches In the same order.

**Comment by julie-sullivan** [comment]
Moved to #26

**Pull request closed without merging**
