### PR TITLE
Csv/Tsv Validator

### PR DESCRIPTION
**Pull request by deepakkumar96**
Add a csv/tsv validaotor
- add dependency to 'univocity-parsers' for parsing csv/tsv files
- using 'edit distance' as the technique for measuring inconsistency
  of data in csv/tsv files

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Can we increment this version to `0.1.3` (or `0.3.0` -- whichever you choose). 
That way I can publish the JAR for use in my app.

**Comment by julie-sullivan** [comment]
```
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.1.jar -f=/data/flymine/annotation_matrix.csv -t=csv
Validating csv file...
Invalid validator type
```

It doesn't seem like `csv` is a valid type?

Also it's not on the help output:

```
                            ValidatorType, fasta is used as default if not provided
                            possible values:
                             fasta,
                             fasta-dna,
                             fasta-rna,
                             fasta-protein,
                            gff3
```

**Comment by deepakkumar96** [comment]
You might be use a jar that is build from Gff validator PR, I have included
csv jar in Google drive share folder

**Comment by julie-sullivan** [comment]
The first CSV file I tried, it failed:

```
Validating csv file...
java.lang.ArrayIndexOutOfBoundsException - 512
Hint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
```

It had 858 columns. Not sure we should have an arbitrary cut off.

**Comment by julie-sullivan** [comment]
Another file failed (`Drosophila_2.na35.annot.csv`)

```
Validating csv file...
Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096). 
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
```

**Comment by deepakkumar96** [comment]
Let me check, csv validator is not yet complete, my mistake, can you share
the file you are validating?

**Comment by julie-sullivan** [comment]
I am guessing the tab is on the TODO list too! :)

```
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.3.jar -f=/data/kegg/map_title.tab -t=csv
Validating csv file...
Result : Valid File!!
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.3.jar -f=/data/kegg/map_title.tab -t=tab
Validating tab file...
Invalid validator type
julie ~/git/biovalidator $ java -jar build/libs/biovalidator-fat-0.1.3.jar -f=/data/kegg/map_title.tab -t=tsv
Validating tsv file...
Invalid validator type

```

**Comment by julie-sullivan** [comment]
> Let me check, csv validator is not yet complete, my mistake, can you share the file you are validating?

Sure! I've uploaded both CSV files to our google drive, in the `data` directory.

**Comment by julie-sullivan** [comment]
Moved to #26

**Pull request closed without merging**
