### PR TITLE
Docs and release_notes

### PR DESCRIPTION
**Pull request by deepakkumar96**
- Add documentation on installation and uses of the library.
- Also added validation rules followed by Fasta and GFF3 validator
- Release_Note

### CODE REVIEW

**Comment by julie-sullivan** [comment]
This all looks good (at a glance!)

Can you provide details:

* purpose of pull request
* how I should test

**Comment by julie-sullivan** [comment]
Replace this:
```
gradle createFatJar
```
with this:
```
./gradlew createFatJar
```
If they use their own gradle version, there may be compatibility issues. We want them to use our wrapper.

**Comment by julie-sullivan** [comment]
```
java -jar biovalidator-0.1.0.jar --help
```
If you run the jar command, I think the JAR ends up in `build/libs`. Can you confirm?

**Comment by deepakkumar96** [comment]
> should be this because we want them to use our provided gradle wrapper:
> 
> ```
> ./gradlew createFatJar
> ```
> 
> If they use their own gradle version, there may be compatibility issues.

If we want to use biovalidator jar as a Runnable jar, then jar should be build with all the dependencies, that is all this task(createFatJar) does, It builds a jar with all dependencies, not just .class files.

**Comment by deepakkumar96** [comment]
> ```
> java -jar biovalidator-0.1.0.jar --help
> ```
> 
> If you run the jar command, I think the JAR ends up in `build/libs`. Can you confirm?

if you execute createFatJar('gradle createFatJar') it will create a fat-jar with all dependencies in 'build//libs'

**Comment by julie-sullivan** [comment]
> > should be this because we want them to use our provided gradle wrapper:
> > ```
> > ./gradlew createFatJar
> > ```
> > 
> > 
> > If they use their own gradle version, there may be compatibility issues.
> 
> If we want to use biovalidator jar as a Runnable jar, then jar should be build with all the dependencies, that is all this task(createFatJar) does, It builds a jar with all dependencies, not just .class files.

I've updated my comment to be clearer (I hope!).

The instructions you have in the docs are incorrect, and need to be updated.

**Comment by julie-sullivan** [comment]
> > ```
> > java -jar biovalidator-0.1.0.jar --help
> > ```
> > 
> > 
> > If you run the jar command, I think the JAR ends up in `build/libs`. Can you confirm?
> 
> if you execute createFatJar('gradle createFatJar') it will create a fat-jar with all dependencies in 'build//libs'

Therefore the instructions you have in the docs are incorrect, and need to be updated.

**Comment by julie-sullivan** [comment]
Moved to #26

**Pull request closed without merging**
