### PR TITLE
BioValidator-API AND Fasta-Validator

### PR DESCRIPTION
**Pull request by deepakkumar96**
Schema validator API and Fasta Validator
- Add common API for schema validator
- Add FASTA validator (Both DNA and PROTEIN sequence validator)
- Add Command-line utitlity to validate from terminal

### CODE REVIEW

**Comment by julie-sullivan** [comment]
src/main/java/org/intermine/biovalidator/utils/StringUtils.java

Could we use the apache commons one instead? As it does this too:

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html

**Comment by deepakkumar96** [comment]
> src/main/java/org/intermine/biovalidator/utils/StringUtils.java
> 
> Could we use the apache commons one instead? As it does this too:
> 
> https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html

Yes, sure! Initially, I thought not to include a dependency for just one or two methods.

**Comment by julie-sullivan** [comment]
yes!! it's always a trade off isn't it!! You are right though, I agree an extra dep isn't worth it EXCEPT:

* it's apache commons
* we are likely going to have more string manipulation / validation methods. so might get used more!

(I am being very picky here, i know!! :))

**Comment by deepakkumar96** [comment]
> yes!! it's always a trade off isn't it!! You are right though, I agree an extra dep isn't worth it EXCEPT:
> 
> * it's apache commons
> * we are likely going to have more string manipulation / validation methods. so might get used more!
> 
> (I am being very picky here, i know!! :))

Yes, Yes, GFF3 validator will require lots of string manipulation.

**Comment by julie-sullivan** [comment]
in general:

* neat code
* small methods
* well named methods and variables

I was able to understand your code, and what you were trying to do.

The tests look thorough too!

Great job! :)

**Comment by julie-sullivan** [comment]
There is ONE small thing that I am not thrilled with (although this is what i would have done too probably!!):

```
        switch (type) {
            case FASTA:
                return ofType(new FastaValidator(reader, SequenceType.ALL));
            case FASTA_DNA:
                return ofType(new FastaValidator(reader, SequenceType.DNA));
            case FASTA_RNA:
                return ofType(new FastaValidator(reader, SequenceType.RNA));
            case FASTA_PROTEIN:
                return ofType(new FastaValidator(reader, SequenceType.PROTEIN));
            default:
                throw new IllegalArgumentException("invalid validator type");
        }
```

Because we hope to ideally end up with 20 or so file types, is this the *best* way we can do this? Thinking of maintainability, least amount of bugs etc. 

I am going to merge the pull request but maybe think on it a little bit? This might be the best way! :)

**Comment by deepakkumar96** [comment]
Thank you, great to hear this!

**Comment by deepakkumar96** [comment]
Yes, you right, as the number of validator increase that switch case get
messy!!, I will further work on improving that switch case.

**Pull request merged**
